on: release
name: Handle Release
jobs:
  upload:
    name: Upload Hez
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Upload
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: 'qmk_firmware/*.hex'
